// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kythe/proto/filetree.proto

package filetree_go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CorpusRootsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CorpusRootsRequest) Reset()         { *m = CorpusRootsRequest{} }
func (m *CorpusRootsRequest) String() string { return proto.CompactTextString(m) }
func (*CorpusRootsRequest) ProtoMessage()    {}
func (*CorpusRootsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_filetree_71f9ffa1667e3fe1, []int{0}
}
func (m *CorpusRootsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorpusRootsRequest.Unmarshal(m, b)
}
func (m *CorpusRootsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorpusRootsRequest.Marshal(b, m, deterministic)
}
func (dst *CorpusRootsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorpusRootsRequest.Merge(dst, src)
}
func (m *CorpusRootsRequest) XXX_Size() int {
	return xxx_messageInfo_CorpusRootsRequest.Size(m)
}
func (m *CorpusRootsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CorpusRootsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CorpusRootsRequest proto.InternalMessageInfo

type CorpusRootsReply struct {
	Corpus               []*CorpusRootsReply_Corpus `protobuf:"bytes,1,rep,name=corpus,proto3" json:"corpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CorpusRootsReply) Reset()         { *m = CorpusRootsReply{} }
func (m *CorpusRootsReply) String() string { return proto.CompactTextString(m) }
func (*CorpusRootsReply) ProtoMessage()    {}
func (*CorpusRootsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_filetree_71f9ffa1667e3fe1, []int{1}
}
func (m *CorpusRootsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorpusRootsReply.Unmarshal(m, b)
}
func (m *CorpusRootsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorpusRootsReply.Marshal(b, m, deterministic)
}
func (dst *CorpusRootsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorpusRootsReply.Merge(dst, src)
}
func (m *CorpusRootsReply) XXX_Size() int {
	return xxx_messageInfo_CorpusRootsReply.Size(m)
}
func (m *CorpusRootsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CorpusRootsReply.DiscardUnknown(m)
}

var xxx_messageInfo_CorpusRootsReply proto.InternalMessageInfo

func (m *CorpusRootsReply) GetCorpus() []*CorpusRootsReply_Corpus {
	if m != nil {
		return m.Corpus
	}
	return nil
}

type CorpusRootsReply_Corpus struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Root                 []string `protobuf:"bytes,2,rep,name=root,proto3" json:"root,omitempty"`
	BuildConfiguration   []string `protobuf:"bytes,3,rep,name=build_configuration,json=buildConfiguration,proto3" json:"build_configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CorpusRootsReply_Corpus) Reset()         { *m = CorpusRootsReply_Corpus{} }
func (m *CorpusRootsReply_Corpus) String() string { return proto.CompactTextString(m) }
func (*CorpusRootsReply_Corpus) ProtoMessage()    {}
func (*CorpusRootsReply_Corpus) Descriptor() ([]byte, []int) {
	return fileDescriptor_filetree_71f9ffa1667e3fe1, []int{1, 0}
}
func (m *CorpusRootsReply_Corpus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorpusRootsReply_Corpus.Unmarshal(m, b)
}
func (m *CorpusRootsReply_Corpus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorpusRootsReply_Corpus.Marshal(b, m, deterministic)
}
func (dst *CorpusRootsReply_Corpus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorpusRootsReply_Corpus.Merge(dst, src)
}
func (m *CorpusRootsReply_Corpus) XXX_Size() int {
	return xxx_messageInfo_CorpusRootsReply_Corpus.Size(m)
}
func (m *CorpusRootsReply_Corpus) XXX_DiscardUnknown() {
	xxx_messageInfo_CorpusRootsReply_Corpus.DiscardUnknown(m)
}

var xxx_messageInfo_CorpusRootsReply_Corpus proto.InternalMessageInfo

func (m *CorpusRootsReply_Corpus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CorpusRootsReply_Corpus) GetRoot() []string {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *CorpusRootsReply_Corpus) GetBuildConfiguration() []string {
	if m != nil {
		return m.BuildConfiguration
	}
	return nil
}

type DirectoryRequest struct {
	Corpus               string   `protobuf:"bytes,1,opt,name=corpus,proto3" json:"corpus,omitempty"`
	Root                 string   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryRequest) Reset()         { *m = DirectoryRequest{} }
func (m *DirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*DirectoryRequest) ProtoMessage()    {}
func (*DirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_filetree_71f9ffa1667e3fe1, []int{2}
}
func (m *DirectoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryRequest.Unmarshal(m, b)
}
func (m *DirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryRequest.Marshal(b, m, deterministic)
}
func (dst *DirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryRequest.Merge(dst, src)
}
func (m *DirectoryRequest) XXX_Size() int {
	return xxx_messageInfo_DirectoryRequest.Size(m)
}
func (m *DirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryRequest proto.InternalMessageInfo

func (m *DirectoryRequest) GetCorpus() string {
	if m != nil {
		return m.Corpus
	}
	return ""
}

func (m *DirectoryRequest) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *DirectoryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DirectoryReply struct {
	Subdirectory         []string `protobuf:"bytes,1,rep,name=subdirectory,proto3" json:"subdirectory,omitempty"`
	File                 []string `protobuf:"bytes,2,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryReply) Reset()         { *m = DirectoryReply{} }
func (m *DirectoryReply) String() string { return proto.CompactTextString(m) }
func (*DirectoryReply) ProtoMessage()    {}
func (*DirectoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_filetree_71f9ffa1667e3fe1, []int{3}
}
func (m *DirectoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryReply.Unmarshal(m, b)
}
func (m *DirectoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryReply.Marshal(b, m, deterministic)
}
func (dst *DirectoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryReply.Merge(dst, src)
}
func (m *DirectoryReply) XXX_Size() int {
	return xxx_messageInfo_DirectoryReply.Size(m)
}
func (m *DirectoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryReply proto.InternalMessageInfo

func (m *DirectoryReply) GetSubdirectory() []string {
	if m != nil {
		return m.Subdirectory
	}
	return nil
}

func (m *DirectoryReply) GetFile() []string {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*CorpusRootsRequest)(nil), "kythe.proto.CorpusRootsRequest")
	proto.RegisterType((*CorpusRootsReply)(nil), "kythe.proto.CorpusRootsReply")
	proto.RegisterType((*CorpusRootsReply_Corpus)(nil), "kythe.proto.CorpusRootsReply.Corpus")
	proto.RegisterType((*DirectoryRequest)(nil), "kythe.proto.DirectoryRequest")
	proto.RegisterType((*DirectoryReply)(nil), "kythe.proto.DirectoryReply")
}

func init() {
	proto.RegisterFile("kythe/proto/filetree.proto", fileDescriptor_filetree_71f9ffa1667e3fe1)
}

var fileDescriptor_filetree_71f9ffa1667e3fe1 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xbc, 0x29, 0x85, 0x4e, 0x45, 0xcb, 0x28, 0x12, 0x22, 0xd2, 0xba, 0x78, 0xe8,
	0x29, 0x85, 0x7a, 0xf5, 0x64, 0x45, 0xf4, 0x24, 0x44, 0xef, 0x92, 0xa6, 0xd3, 0x76, 0x71, 0xdb,
	0x89, 0x9b, 0x4d, 0xa1, 0x1f, 0xca, 0x93, 0x5f, 0x50, 0x76, 0xfb, 0x87, 0x4d, 0xa1, 0x9e, 0x76,
	0xe6, 0x37, 0xb3, 0xcf, 0xcc, 0x3c, 0x10, 0x7f, 0xae, 0xcd, 0x9c, 0x06, 0x85, 0x66, 0xc3, 0x83,
	0xa9, 0x54, 0x64, 0x34, 0x51, 0xe2, 0x52, 0x6c, 0xbb, 0xda, 0x26, 0x11, 0x17, 0x80, 0x23, 0xd6,
	0x45, 0x55, 0xa6, 0xcc, 0xa6, 0x4c, 0xe9, 0xab, 0xa2, 0xd2, 0x88, 0x9f, 0x00, 0x3a, 0x35, 0x5c,
	0xa8, 0x35, 0xde, 0x43, 0x33, 0x77, 0x2c, 0x0a, 0x7a, 0x61, 0xbf, 0x3d, 0xbc, 0x4d, 0x3c, 0xa1,
	0xe4, 0xb0, 0x7d, 0x07, 0xb6, 0x7f, 0xe2, 0x0c, 0x9a, 0x1b, 0x82, 0x08, 0x8d, 0x65, 0xb6, 0xa0,
	0x28, 0xe8, 0x05, 0xfd, 0x56, 0xea, 0x62, 0xcb, 0x34, 0xb3, 0x89, 0xfe, 0xf7, 0x42, 0xcb, 0x6c,
	0x8c, 0x03, 0x38, 0x1f, 0x57, 0x52, 0x4d, 0x3e, 0x72, 0x5e, 0x4e, 0xe5, 0xac, 0xd2, 0x99, 0x91,
	0xbc, 0x8c, 0x42, 0xd7, 0x82, 0xae, 0x34, 0xf2, 0x2b, 0x22, 0x85, 0xce, 0xa3, 0xd4, 0x94, 0x1b,
	0xd6, 0xeb, 0xed, 0x25, 0x78, 0xe9, 0x2d, 0x6d, 0xc7, 0x6d, 0x33, 0x6f, 0x60, 0xb0, 0x1f, 0x88,
	0xd0, 0x28, 0x32, 0x33, 0x8f, 0xc2, 0x0d, 0xb3, 0xb1, 0x78, 0x86, 0x53, 0x4f, 0xd3, 0xda, 0x20,
	0xe0, 0xa4, 0xac, 0xc6, 0x93, 0x1d, 0x74, 0x66, 0xb4, 0xd2, 0x1a, 0xb3, 0x4a, 0xd6, 0xf4, 0xdd,
	0x39, 0x36, 0x1e, 0x7e, 0x07, 0x70, 0xf6, 0x24, 0x15, 0xbd, 0x6b, 0xa2, 0x37, 0xd2, 0x2b, 0x99,
	0x13, 0xbe, 0x42, 0xdb, 0xf3, 0x0d, 0xbb, 0xc7, 0x1d, 0x75, 0xd7, 0xc4, 0xd7, 0x7f, 0x5a, 0x2e,
	0xfe, 0xe1, 0x0b, 0xb4, 0xf6, 0xeb, 0x62, 0xbd, 0xfb, 0xd0, 0x9a, 0xf8, 0xea, 0x58, 0xd9, 0x49,
	0x3d, 0xdc, 0x40, 0x37, 0xe7, 0x45, 0x32, 0x63, 0x9e, 0x29, 0x4a, 0x26, 0xb4, 0x32, 0xcc, 0xaa,
	0xf4, 0xff, 0x8c, 0x9b, 0xee, 0xb9, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x5f, 0x66, 0x19,
	0x6e, 0x02, 0x00, 0x00,
}
